### ISSUE TITLE
Add JDK8 support?

### ISSUE THREAD

**Issue by 1s1y** [getsentry/sentry-maven-plugin#33]
### Problem Statement

Currently, the plugin maven.compiler.target is 11.
However the Java SDK supports Java 1.8 and above.
Is there any special reason for using JDK11?

**Comment by adinauer** [comment]
Hello @1s1y. Thanks for opening this issue. We'll look into it and update here.

**Comment by adinauer** [comment]
@1s1y we've just released [0.0.6](https://github.com/getsentry/sentry-maven-plugin/releases/tag/0.0.6) which should be compatible with JDK8. Feedback is highly appreciated in case you decide to give it a try.
