### ISSUE TITLE
Maven error in window system，Can you be compatible with the window system。[ERROR] around Ant part ...<exec executable="/bin/sh">... @ 4:32

### ISSUE THREAD

**Issue by gang0713** [getsentry/sentry-maven-plugin#5]
### Maven Version

3.92

### Version

0.0.2

### Sentry SDK Version

6.23.0

### Steps to Reproduce

  Maven error in window system，Can you be compatible with the window system。
<executions>
                    <execution>
                        <phase>install</phase>
                        <goals>
                            <goal>uploadSourceBundle</goal>
                        </goals>
                    </execution>
                </executions>

### Expected Result

Successfully packaged normally

### Actual Result

[ERROR] around Ant part ...<exec executable="/bin/sh">... @ 4:32 in D:\soft\workspace\my-cloud\my-sync-biz\target\antrun\build-main.xml
```[tasklist]
### Tasks
```

**Comment by adinauer** [comment]
Thanks for the request @gang0713, we'll look into supporting builds on Windows as well. Can't give a timeline at the moment though.

**Comment by adinauer** [comment]
@gang0713 we've just released https://github.com/getsentry/sentry-maven-plugin/releases/tag/0.0.3 which should arrive in Maven repositories soon.
