### ISSUE TITLE
Allow disabling the plugin using the comand line

### ISSUE THREAD

**Issue by vigenere23** [getsentry/sentry-maven-plugin#60]
### Problem Statement

Maybe it's moe of a problem from Maven's end, but let's say you want to dockerize a project that is configured to upload Sentry source bundles, but you don't have a sentry Auth key or want to provide one during the image build, it would be nice to not have to mingle with the `pom.xml` configuration and simply be able to pass either an env variable or a property to disable the plugin.

### Solution Brainstorm

- Have the plugin check for an env-variable and/or a system property before executing, thus allowing it to be disabled dynamically.

**Comment by adinauer** [comment]
Hello @vigenere23, you could add a
```
    <properties>
		...
        <sentry.skip>false</sentry.skip>
    </properties>
```

and use that in our <plugin><configuration> block like:
```
...
		<skip>${sentry.skip}</skip>
    </configuration>
</plugin>
```

Then when running the command you could do something like `./mvnw package -Dsentry.skip=true`. 

Using `<sentry.skip>${env.SENTRY_SKIP}</sentry.skip>` enable/disable Sentry via the `SENTRY_SKIP` environment variable.

**Comment by vigenere23** [comment]
Yes that's the *solution* I have seen. I was more wondering about the case were we do not own the `pom.xml` and thus have to find a way that does not require it to change. Is that more of a convention problem with Maven and how the tools are generaly made?
