### ISSUE TITLE
Failure to upload source bundle with sentry-cli on Windows if project.build.directory contains whitespace

### ISSUE THREAD

**Issue by btpnlsl** [getsentry/sentry-maven-plugin#62]
### Maven Version

3.9.6

### Version

0.0.7

### Sentry SDK Version

7.6.0

### Steps to Reproduce

1. On a Windows computer, create a new Spring Boot project in a subdirectory which has a space in it (e.g. "C:\Users\FirstName LastName\Documents\Project")
2. Add `sentry-maven-plugin` and `sentry-spring-boot-starter` to the project
3. Configure `sentry-maven-plugin` to upload a source bundle for the project
4. Build the project with maven from the command line (use '-X' flag for debug logs from maven)

### Expected Result

The project should build correctly and upload a source bundle.

### Actual Result

Invoking `sentry-cli` to upload the source bundle will fail because the plugin is not enclosing directory names in quotes.

`C:\Users\FOOBAR~1\AppData\Local\Temp\.sentry-cli13348786534883263189.exe --log-level=debug [......] --output=C:\Users\Foo Bar\Documents\project\target\sentry\source-bundle [...] C:\Users\Foo Bar\project\src\main\java`

**Comment by adinauer** [comment]
Thanks for the report @btpnlsl we'll make sure to fix this.
